# list-lab-reports.ps1 — list synthetic lab PDFs generated by generate-lab-pdf.ps1
#
# Lab PDFs are written to ./lab-reports/lab-{pid}-{yyyyMMdd-HHmmss}.pdf.
# This script enumerates that directory, parses pid + date from each filename,
# joins against patient_data for the full name, and prints a table sorted by
# patient id ascending, then date descending.
#
# Usage:
#   ./list-lab-reports.ps1 5          # reports for patient pid=5
#   ./list-lab-reports.ps1 -All       # reports for every patient

[CmdletBinding(DefaultParameterSetName = "Single")]
param(
    [Parameter(Mandatory, Position = 0, ParameterSetName = "Single")]
    [int]$PatientId,

    [Parameter(Mandatory, ParameterSetName = "All")]
    [switch]$All,

    [string]$ProjectName = "development-easy",
    [string]$ReportsDir
)

$ErrorActionPreference = "Stop"

function Confirm-DockerCompose {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker CLI was not found. Install Docker Desktop, then run this script again."
    }

    & docker compose version | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose v2 was not found. Install or enable the Docker Compose plugin, then run this script again."
    }
}

function Confirm-MysqlContainerRunning {
    $running = & docker compose --project-name $ProjectName ps --services --filter "status=running"
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose ps failed with exit code $LASTEXITCODE. Is the '$ProjectName' stack started?"
    }

    if (-not ($running -contains "mysql")) {
        throw "The 'mysql' service is not running for project '$ProjectName'. Start it with: docker compose --project-name $ProjectName up --detach --wait"
    }
}

function Get-PatientNames {
    param([Parameter(Mandatory)][int[]]$PatientIds)

    if ($PatientIds.Count -eq 0) { return @{} }

    $idList = ($PatientIds | Sort-Object -Unique) -join ','
    $sql = @"
SELECT
    pid,
    TRIM(BOTH ' ' FROM REGEXP_REPLACE(CONCAT_WS(' ', NULLIF(TRIM(fname), ''), NULLIF(TRIM(mname), ''), NULLIF(TRIM(lname), '')), '[[:space:]]+', ' ')) AS full_name
FROM patient_data
WHERE pid IN ($idList);
"@

    $rawOutput = & docker compose --project-name $ProjectName exec -T mysql mariadb -uopenemr -popenemr openemr --batch --skip-column-names -e $sql
    if ($LASTEXITCODE -ne 0) {
        throw "Patient name lookup failed with exit code $LASTEXITCODE."
    }

    $names = @{}
    foreach ($line in $rawOutput) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        $fields = $line -split "`t", 2
        if ($fields.Count -lt 2) { continue }
        $names[[int]$fields[0]] = $fields[1]
    }
    return $names
}

# --- Main ---

if ([string]::IsNullOrWhiteSpace($ReportsDir)) {
    $ReportsDir = Join-Path $PSScriptRoot "lab-reports"
}

if (-not (Test-Path -LiteralPath $ReportsDir)) {
    Write-Host "No lab reports directory found at: $ReportsDir"
    Write-Host "Generate one with ./generate-lab-pdf.ps1 first."
    return
}

$files = @(Get-ChildItem -LiteralPath $ReportsDir -Filter "lab-*.pdf" -File -ErrorAction SilentlyContinue)
if ($files.Count -eq 0) {
    Write-Host "No lab reports found in: $ReportsDir"
    return
}

$pattern = '^lab-(\d+)-(\d{8})-(\d{6})\.pdf$'

$reports = foreach ($file in $files) {
    if ($file.Name -notmatch $pattern) { continue }

    $reportDate = [DateTime]::ParseExact(
        "$($matches[2])-$($matches[3])",
        'yyyyMMdd-HHmmss',
        [System.Globalization.CultureInfo]::InvariantCulture
    )

    [pscustomobject]@{
        ID         = [int]$matches[1]
        ReportDate = $reportDate
        File       = $file.Name
        FullPath   = $file.FullName
        SizeKB     = [math]::Round($file.Length / 1KB, 1)
    }
}

if ($PSCmdlet.ParameterSetName -eq "Single") {
    $reports = @($reports | Where-Object { $_.ID -eq $PatientId })
}
else {
    $reports = @($reports)
}

if ($reports.Count -eq 0) {
    if ($PSCmdlet.ParameterSetName -eq "Single") {
        Write-Host "No lab reports found for patient pid=$PatientId in: $ReportsDir"
    }
    else {
        Write-Host "No parseable lab report files found in: $ReportsDir"
    }
    return
}

Confirm-DockerCompose
Confirm-MysqlContainerRunning

$patientIds = @($reports | ForEach-Object { $_.ID } | Sort-Object -Unique)
$names = Get-PatientNames -PatientIds $patientIds

$enriched = foreach ($r in $reports) {
    $patientName = if ($names.ContainsKey($r.ID)) { $names[$r.ID] } else { '<unknown>' }
    [pscustomobject]@{
        ID      = $r.ID
        Patient = $patientName
        Date    = $r.ReportDate.ToString('yyyy-MM-dd HH:mm:ss')
        SizeKB  = $r.SizeKB
        File    = $r.File
    }
}

$sorted = $enriched | Sort-Object `
    @{ Expression = 'ID';   Ascending = $true },
    @{ Expression = 'Date'; Ascending = $false }

$sorted | Format-Table -AutoSize
Write-Host "Total lab reports: $(@($sorted).Count)"
